apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

helmCharts:
- name: nginx
  repo: https://charts.bitnami.com/bitnami
  includeCRDs: true
  valuesFile: values.yaml
  version: 14.1.0