apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: nginx
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values.yaml
  version: 14.0.0

patches:
- path: deletesvc.yaml
