apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: guestbook
  repo: https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook
  includeCRDs: true
  valuesFile: values.yaml